sonar.projectKey=ilnur097_github_go-from-scratch-project-244
sonar.organization=ilnur097_github
sonar.sources=.
sonar.exclusions=**/*_test.go,**/testdata/**
sonar.go.coverage.reportPaths=coverage.out
